DROP TABLE IF EXISTS books;
DROP TABLE IF EXISTS users;

CREATE TABLE books (
id INT AUTO_INCREMENT PRIMARY KEY,
author VARCHAR (250) NOT NULL,
title VARCHAR (250) NOT NULL,
size INT DEFAULT NULL
);

CREATE TABLE users (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR (250) NOT NULL,
surname VARCHAR (250) NOT NULL,
age INT NOT NULL,
email VARCHAR (250) NOT NULL,
login VARCHAR (250) NOT NULL,
password VARCHAR (250) NOT NULL
);